### ISSUE TITLE
🚨 Scénarios Killercoda down 🚨 

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-api#110]
cf https://github.com/opt-nc/colisnc-api/issues/86#issuecomment-1188792139

et fait suite à https://github.com/opt-nc/colisnc-api/issues/98

**Comment by Dougniel** [comment]
Duplicate of https://github.com/opt-nc/katacoda-opt-labs/issues/48

**Comment by adriens** [comment]
Yep, je viens de valider, c'est vraiment rapide et super clean :ok_hand:
