### ISSUE TITLE
Upgrade vers java 17

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-api#18]
- [ ] Basculer le build en Java 17
- [ ] Pousser l'image Docker en java 17

**Comment by adriens** [comment]
Je crois qu'on a zappé ça.

**Comment by Dougniel** [comment]
@adriens, pourquoi le build matrix sur 8 et 11 si le build est en 17 et l'image docker aussi ?

**Comment by adriens** [comment]
> @adriens, pourquoi le build matrix sur 8 et 11 si le build est en 17 et l'image docker aussi ?

> build matrix 8,11 et 17

Pour montrer ce que l'on utiliser réellement en Java. On figera 17 dès lors qu'on utilisera des features dispos sur 17 seulement

> Image en 17

On en aura besoin pour la partie native dès qu'elle sera mûre côté SB

**Comment by Dougniel** [comment]
@adriens, 
Autant sur le sdk cela importe de savoir si c'est compatible avec les différentes versions de JDK car c'est fait pour être utilisé à part entière
Autant sur l'api packagé en image docker je trouve que c'est du temps de compile, d'utilisation de ressources GH qui n'apportent rien à part de l'attente supplémentaire et que si un jour on a besoin d'utiliser des nouvelles features du JDK 17 il faudra changer le build pour que ça passe, autant dire un frein supplémentaire et aussi un risque de mauvaise interprétation du dev "ah visiblement il faut que ça fonctionne en Java8"... bref, pour moi faut juste avancer quand on peut

**Comment by adriens** [comment]
> Autant sur l'api packagé en image docker je trouve que c'est du temps de compile...

Sujet du ticket changé en conséquence. Noter qu'en open source, la CI est "gratuite" et qu'il est toujours bon de savoir avec quels runtimes on est compatibles.

> Autant sur le sdk cela importe de savoir si c'est compatible avec les différentes versions de JDK car c'est fait pour être utilisé à part entière

Sachant que le premier commit qui fera planter la CI sur un runtime < 8, on droppera le build < 17 : on saura en revanche via la CI  à partir de quel commit on dropper le support des anciens runtime. Bien faire gaffe que cela aura un impact sur l'API et donc l'image

**Comment by adriens** [comment]
👍 
![image](https://user-images.githubusercontent.com/5235127/145149489-e85eb81b-3faa-4ac7-9a51-18a338e705b7.png)
