### ISSUE TITLE
:warning:  Springboot Devtools actif dans l'image docker

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/colisnc-api#23]
![image](https://user-images.githubusercontent.com/39691264/145144417-98bbef3d-6057-47c8-918a-d1758bc55cf2.png)

**Comment by Dougniel** [comment]
Toujours pas

**Comment by Dougniel** [comment]
Toujours pas

**Comment by Dougniel** [comment]
@adriens, @mbarre un point important sur lequel je suis tombé : jib ne prends pas le gros jar de SpringBoot avec tout dedans, il prends chaque jar ce qui fait que le mécanisme SpringBoot pour désactiver le devtools en prod ne s'applique pas, c'est pour cela que devtools était actif dans l'image Docker 

Pour que ça passe, il faut passer par un plugin spring-boot de Jib : 
```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>3.1.4</version>

  <dependencies>
    <dependency>
      <groupId>com.google.cloud.tools</groupId>
      <artifactId>jib-spring-boot-extension-maven</artifactId>
      <version>0.1.0</version>
    </dependency>
  </dependencies>

  <configuration>
    ...
    <pluginExtensions>
      <pluginExtension>
        <implementation>com.google.cloud.tools.jib.maven.extension.springboot.JibSpringBootExtension</implementation>
      </pluginExtension>
    </pluginExtensions>
  </configuration>
</plugin>
```
https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-spring-boot-extension-maven

**Comment by adriens** [comment]
OULA, super bien vu, en effet !
A injecter dans la repo template à venir pour le coup 👍
