### ISSUE TITLE
Passer la branch `main` en branche par défaut

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/colisnc-api#25]
@adriens, j'ai préparé la branche `main`, pourrais tu la positionner en tant que branche par défaut stp ?

**Comment by adriens** [comment]
Je men occupe yes

**Comment by adriens** [comment]
Yep, c'est fait
![image](https://user-images.githubusercontent.com/5235127/145167316-ecb8d572-1c47-409d-932c-a528a2308b22.png)
