### ISSUE TITLE
Implement /management/health

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-api#74]
```
# Run current stable image in background
docker run -d --rm -p 8080:8080 --name health optnc/colisnc-api:stable
# Ask actuator
http :8080/management/health
# Kill all containers
docker kill health
```

![image](https://user-images.githubusercontent.com/5235127/168170497-2f0e5dd2-b31e-4b32-92a7-eddf34629c7f.png)

**Comment by Dougniel** [comment]
https://github.com/opt-nc/GLIA/issues/582#issuecomment-1126570555, déjà sur `/actuator/health`

**Comment by adriens** [comment]
:ok_hand:
