### ISSUE TITLE
:rotating_light: Problème de dépendances `colisnc-sdk`

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/colisnc-api#81]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/39691264/174542743-754fb8f9-27e3-4a67-a9f5-30fb415ba742.png">

Effectivement, les dépendances dans `colins-sdk` ne sont pas remontés dans le [pom.xml](https://jitpack.io/com/github/opt-nc/colisnc-sdk/v2.0.3/colisnc-sdk-v2.0.3.pom) du sdk :

<img width="480" alt="image" src="https://user-images.githubusercontent.com/39691264/174543036-a88c4c71-a1aa-42bb-baa2-d0200272afe1.png">

cela semble avoir toujours été le cas, alors la dépendance `jsoup` était tirée par une autre dépendance et ça passait

la conf du plugin shade dans `colins-sdk` semble être la cause du problème

**Comment by adriens** [comment]
AH ben merde c nouveau ça :hankey:

**Comment by adriens** [comment]
Ok, il bloque tout le reste celui-là 😓

**Comment by adriens** [comment]
C'est moche aussi les relicats hisoriques de `com.github.adriens` :sweat_smile:

**Comment by adriens** [comment]
YES :heavy_heart_exclamation:
