### ISSUE TITLE
:bug: Country null (Slovénie, Nouvelle-calédonie,)

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-api#86]
Sur `CA107308006` on a un souci avec `country` que l'on arrive pas à remonter proprement : 

```json
"country": null,
```

Tous les détails : 

```json
[
    {
        "country": null,
        "date": "2019-09-09T09:41:12",
        "informations": "",
        "itemId": "CA107308006SI",
        "localisation": "NOUMEA CDC",
        "localization": {
            "longName": "",
            "name": "",
            "url": ""
        },
        "pays": "Nouvelle-Calédonie",
        "rawDateHeure": "09/09/2019 09:41:12",
        "status": "COLIS_LIVRE",
        "typeEvenement": "Votre courrier/colis a été livré"
    },
    {
        "country": null,
        "date": "2019-09-06T15:38:04",
        "informations": "",
        "itemId": "CA107308006SI",
        "localisation": "NOUMEA-CTP",
        "localization": {
            "longName": "",
            "name": "",
            "url": ""
        },
        "pays": "Nouvelle-Calédonie",
        "rawDateHeure": "06/09/2019 15:38:04",
        "status": "COLIS_EN_COURS_ACHEMINEMENT",
        "typeEvenement": "Votre courrier/colis est en cours d'acheminement."
    },
    {
        "country": null,
        "date": "2019-09-06T10:43:27",
        "informations": "",
        "itemId": "CA107308006SI",
        "localisation": "NOUMEA-CTP",
        "localization": {
            "longName": "",
            "name": "",
            "url": ""
        },
        "pays": "Nouvelle-Calédonie",
        "rawDateHeure": "06/09/2019 10:43:27",
        "status": "COLIS_EN_COURS_DEDOUANEMENT",
        "typeEvenement": "Votre courrier/colis est en cours de dédouanement"
    },
    {
        "country": null,
        "date": "2019-09-06T10:43:27",
        "informations": "",
        "itemId": "CA107308006SI",
        "localisation": "NOUMEA-CTP",
        "localization": {
            "longName": "",
            "name": "",
            "url": ""
        },
        "pays": "Nouvelle-Calédonie",
        "rawDateHeure": "06/09/2019 10:43:27",
        "status": "COLIS_ARRIVE_PAYS_DESTINATION",
        "typeEvenement": "Votre courrier/colis est arrivé dans le pays de destination"
    },
    ...
    {
        "country": null,
        "date": "2019-08-09T08:29:00",
        "informations": "",
        "itemId": "CA107308006SI",
        "localisation": "LJUBLJANA 1003",
        "localization": {
            "longName": "",
            "name": "",
            "url": ""
        },
        "pays": "Slovénie",
        "rawDateHeure": "09/08/2019 08:29:00",
        "status": "UNEXPECTED",
        "typeEvenement": "Votre courrier/colis est prêt à quitter son pays d'origine."
    },
    {
        "country": null,
        "date": "2019-08-06T09:37:00",
        "informations": "",
        "itemId": "CA107308006SI",
        "localisation": "2116",
        "localization": null,
        "pays": "Slovénie",
        "rawDateHeure": "06/08/2019 09:37:00",
        "status": "COLIS_PRIS_EN_CHARGE",
        "typeEvenement": "Votre courrier/colis a été pris en charge"
    }
]
```

**Comment by Dougniel** [comment]
@adriens, il semble que le numéro de colis en question ne soit plus dispo : 
<img width="790" alt="image" src="https://user-images.githubusercontent.com/39691264/179468621-c0025ead-d8e0-4b84-928c-f221f5e8b54a.png">

Un autre est disponible ?

**Comment by Dougniel** [comment]
ℹ️ Je ne reproduis ce problème qu'en version native

**Comment by adriens** [comment]
> Je ne reproduis ce problème qu'en version native

WTF... je me demande si c'est pas lié au chargeemnt des locales très lié au jdk , non ? C'est pas une piste ç creuser ?

**Comment by adriens** [comment]
... dans le SDK

**Comment by adriens** [comment]
ici : https://github.com/opt-nc/colisnc-sdk/blob/caad16f39256dad84229ee169cf081603d9671ea/src/main/java/com/adriens/github/colisnc/countries/ListCountriesDefinedLanguage.java#L52

**Comment by Dougniel** [comment]
> ici : https://github.com/opt-nc/colisnc-sdk/blob/caad16f39256dad84229ee169cf081603d9671ea/src/main/java/com/adriens/github/colisnc/countries/ListCountriesDefinedLanguage.java#L52 :
> 
> ```java
> String[] countryCodes = Locale.getISOCountries();
> ```

En effet ça peut jouer, je sais que par défaut ils ne mettent pas toutes les locales pour gagner en tailel

**Comment by adriens** [comment]
> En effet ça peut jouer, je sais que par défaut ils ne mettent pas toutes les locales pour gagner en taille

Ben là ça serait radical quand même. :open_mouth:

**Comment by adriens** [comment]
Ca existe toujours bien sinon https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Locale.IsoCountryCode.html

**Comment by Dougniel** [comment]
Le bug venait de l'appel
```java
locale.getDisplayCountry(Locale.FRANCE)
```
Qui retournait "New Caledonia" au lieu de "Nouvelle Calédonie" _(ce qui reste d'ailleurs conforme à la JavaDoc qui indique que la méthode retourne au pire la version anglaise)_

👉🏼 ajout de paramètres de build

**Comment by adriens** [comment]
Du coup faut faire quoi pour que ça marche ?

![image](https://user-images.githubusercontent.com/5235127/179612223-19c35d1d-5fa9-45e8-94fc-062edd5f04bd.png)


![image](https://user-images.githubusercontent.com/5235127/179612015-b02f59ac-4961-4c3d-a9ad-27ba80e6562f.png)

**Comment by Dougniel** [comment]
> T'as valiidé sur Killercoda ?

J'ai validé en local en récupérant l'image `:develop`

**Comment by Dougniel** [comment]
> Pense à tester sur un env vierge, sur Killercoda c pratique

C'est plus long

ce que je propose c'est plutôt de faire des vrais TU qui servent à quelque-chose maintenant qu'avec Quarkus il peut les jouer sur la version native

**Comment by Dougniel** [comment]
Soucis CI, ok pour la `:develop` mais pas sur la `:latest` : https://github.com/opt-nc/colisnc-api/issues/98#issuecomment-1188829962

**Comment by adriens** [comment]
:eyes:

**Comment by adriens** [comment]
C'est parfait
:point_right: A détailler dans l'article à venir : impact sur la stratégie de tests comme bénéfice direct :moneybag:
