### ISSUE TITLE
:rotating_light: "main branch isn't protected" :fearful: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-api#91]
![image](https://user-images.githubusercontent.com/5235127/178904803-cf04e2c7-e0d7-41e2-bb2a-90fb63acd78a.png)

**Comment by mbarre** [comment]
@adriens ,

je ne suis pas admin du projet, je ne peux pas faire la configuration de ce projet.

**Comment by adriens** [comment]
> je ne suis pas admin du projet, je ne peux pas faire la configuration de ce projet.

Mais siiii, esaie bien, je suis sûr que tu peux le faire :smiling_imp:

**Comment by mbarre** [comment]
C'est fait

**Comment by adriens** [comment]
💪

**Comment by Dougniel** [comment]
J'ai allégé les règles pour permettre de faire une release avec `semantic-release` : 

https://github.com/opt-nc/colisnc-api/issues/98#issuecomment-1188829962

Discussion intéressante si on veut aller plus loin dans la protection des branches : https://github.com/semantic-release/github/issues/175
