### ISSUE TITLE
Migrer sur Quarkus

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-api#98]

**Comment by Dougniel** [comment]
Étrangeté en natif 😳 : 

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/39691264/179695055-96db798d-74b8-45e9-b949-9a8ef8b82380.png">

Mais au moins le message est parlant

**Comment by Dougniel** [comment]
☝️Point intéressant par rapport au [problème de `country=null`](https://github.com/opt-nc/colisnc-api/issues/86), c'est plus parlant cette fois-ci (ça passe pas en douce) : 

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/39691264/179698216-36e99c88-5b06-4268-aa0f-3a7c343b0651.png">

Pour corriger `quarkus.default-locale=fr`

**Comment by Dougniel** [comment]
Soucis sur la release Docker (je ne l'avais pas encore testé avec api-transitaires) :
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/39691264/179707879-0fa9209f-a7b7-4f72-a9a9-a585b89a4a49.png">

**Comment by adriens** [comment]
> Pour corriger `quarkus.default-locale=fr`

Ca me plait, c très explicite :+1:

**Comment by adriens** [comment]
> build natif passé de 2min à 1min

:gun: 

> build CI natif passé de 14min à 4min

:rofl: promesses tenues, et à consigner dans l'article DEV.to, avec quelques comparaisons de build sur GH

> taille de l'image Docker passé de 40 mo à 30 mo

:ok_hand: 

> temps de migration vers Quarkus : 1h30 (cas le plus simple que l'on puisse avoir point_up)

Yes, la facto dans le SDK est efficace :heavy_check_mark:

**Comment by adriens** [comment]
:pray: @lschaeffer313 :people_holding_hands: :heavy_heart_exclamation:

**Comment by Dougniel** [comment]
Bon, maintenant c'est un autre soucis avec la CI, liée a #91 (trop de limitations car sémanticiennes-release ne peux-plus faire de commit): 

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/39691264/179718953-32d16a0b-8108-4e83-bf2f-4711e2ef8698.png">

@adriens, j'ai besoin des droits pour alléger les restrictions

**Comment by adriens** [comment]
> @adriens, j'ai besoin des droits pour alléger les restrictions

C good, vas-y :zap:
